"""Contract tests keeping the canonical manual synchronized with HPCA."""
from __future__ import annotations

import importlib.util
import re
from pathlib import Path

import yaml

from hpca.core.project_schema import validate
from hpca.registry import folder
from hpca.registry.stage import STAGES


ROOT = Path(__file__).resolve().parents[2]
DOCS = ROOT / "docs"


def _all_docs_text() -> str:
    return "\n".join(
        path.read_text(encoding="utf-8")
        for path in DOCS.rglob("*.md")
        if "archive" not in path.parts
    )


def _load_api_generator():
    spec = importlib.util.spec_from_file_location("hpca_docs_api", DOCS / "gen_api_pages.py")
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_all_console_scripts_are_documented() -> None:
    pyproject = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
    scripts_block = pyproject.split("[project.scripts]", 1)[1].split("[", 1)[0]
    commands = re.findall(r"^([\w-]+)\s*=", scripts_block, flags=re.MULTILINE)
    cli = (DOCS / "reference/cli.md").read_text(encoding="utf-8")
    assert commands
    assert not [command for command in commands if f"`{command}" not in cli]


def test_all_registered_stages_are_documented() -> None:
    stages = (DOCS / "workflow/stages.md").read_text(encoding="utf-8")
    assert not [name for name in STAGES if f"`{name}`" not in stages]


def test_api_generator_covers_every_production_module() -> None:
    generator = _load_api_generator()
    discovered = generator.discover_modules(ROOT)
    expected = [
        path for path in (ROOT / "hpca").rglob("*.py")
        if "tests" not in path.relative_to(ROOT).parts
    ]
    assert len(discovered) == len(expected)
    assert len({name for name, _ in discovered}) == len(expected)
    assert len({generator.api_doc_path(name, path) for name, path in discovered}) == len(expected)


def test_documented_project_examples_pass_real_schema() -> None:
    for path in sorted((DOCS / "examples").glob("*.yaml")):
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
        assert validate(data) == [], f"{path.name}: {validate(data)}"


def test_documented_core_paths_match_folder_registry() -> None:
    files = (DOCS / "workflow/files.md").read_text(encoding="utf-8")
    root = Path("/project")
    registered = (
        folder.poscar_dft(root),
        folder.poscar_mlmd(root),
        folder.poscar_cmd(root),
        folder.contcar_dft_preopt(root),
        folder.contcar_mlmd_preopt(root),
        folder.contcar_cmd_preopt(root),
        folder.cmd_data_lammps(root),
        folder.dft_aimd_relax(root),
        folder.dft_vc_contcar(root),
        folder.dft_opt_contcar(root),
        folder.aimd_dataset_dir(root),
    )
    for path in registered:
        assert path.relative_to(root).as_posix() in files


def test_active_docs_do_not_treat_legacy_plans_as_sources() -> None:
    text = _all_docs_text()
    for legacy in (
        "HPCA_PRODUCTION_PLAN.md",
        "PROPOSED_HPCA_WORKFLOW.md",
        "HPCA_END_TO_END_WORKFLOW.md",
        "HPCA_WORKFLOW.md",
        "hpca/orchestrator/PLAN.md",
    ):
        assert legacy not in text


def test_static_markdown_links_resolve() -> None:
    link_pattern = re.compile(r"(?<!!)\[[^]]*]\(([^)]+)\)")
    missing: list[str] = []
    for page in DOCS.rglob("*.md"):
        for raw in link_pattern.findall(page.read_text(encoding="utf-8")):
            target = raw.split("#", 1)[0].strip().strip("<>")
            if not target or "://" in target or target.startswith("#"):
                continue
            if "reference/api/" in target or target.startswith("api/"):
                continue  # generated by docs/gen_api_pages.py
            resolved = (page.parent / target).resolve()
            if not resolved.exists():
                missing.append(f"{page.relative_to(ROOT)} -> {target}")
    assert not missing, "\n".join(missing)


def test_formula_reference_covers_implemented_model_families() -> None:
    formulas = (DOCS / "reference/formulas.md").read_text(encoding="utf-8")
    required = (
        "Mean-squared displacement", "Einstein self-diffusion", "Arrhenius",
        "Nernst–Einstein", "Haven ratio", "Radial distribution", "Van Hove",
        "Velocity autocorrelation", "Lindemann", "Steinhardt", "Vogel–Tammann",
        "Nernst–Planck", "Effective-medium", "Fick diffusion", "SEI/interphase",
        "Allen–Cahn", "KJMA", "Butler–Volmer", "Open-circuit voltage",
        "Vegard", "Critical flaw", "RMSE",
    )
    assert not [name for name in required if name not in formulas]


def test_every_manual_section_is_in_complete_html_builder() -> None:
    spec = importlib.util.spec_from_file_location(
        "hpca_complete_html", DOCS / "build_complete_html.py")
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    expected = {
        path.relative_to(DOCS).as_posix()
        for path in DOCS.rglob("*.md")
        if "reference/api" not in path.as_posix()
    }
    assert set(module.PAGES) == expected
